program UsandoGdiplus;

uses
  Forms,
  uDemoDrawLine in 'Introdução\uDemoDrawLine.pas',
  uDemoDrawString in 'Introdução\uDemoDrawString.pas',
  uDemoDrawLinesAndRectangles in 'Usando a caneta para desenhar linhas e formas\uDemoDrawLinesAndRectangles.pas',
  uDemoPenWidthAndAlignment in 'Usando a caneta para desenhar linhas e formas\uDemoPenWidthAndAlignment.pas',
  uDemoDrawLineCaps in 'Usando a caneta para desenhar linhas e formas\uDemoDrawLineCaps.pas',
  uDemoJoiningLines in 'Usando a caneta para desenhar linhas e formas\uDemoJoiningLines.pas',
  uDemoCustomDashedLine in 'Usando a caneta para desenhar linhas e formas\uDemoCustomDashedLine.pas',
  uDemoLineTexture in 'Usando a caneta para desenhar linhas e formas\uDemoLineTexture.pas',
  uDemoFillSolidColor in 'Usando o pincel para preencher formas\uDemoFillSolidColor.pas',
  uDemoFillHatchPattern in 'Usando o pincel para preencher formas\uDemoFillHatchPattern.pas',
  uDemoFillImageTexture in 'Usando o pincel para preencher formas\uDemoFillImageTexture.pas',
  uDemoTileImage in 'Usando o pincel para preencher formas\uDemoTileImage.pas',
  uDemoLoadDisplayBitmap in 'Usando imagens, bitmaps e metarquivos\uDemoLoadDisplayBitmap.pas',
  uDemoLoadDisplayMetafile in 'Usando imagens, bitmaps e metarquivos\uDemoLoadDisplayMetafile.pas',
  uDemoRecordMetafiles in 'Usando imagens, bitmaps e metarquivos\uDemoRecordMetafiles.pas',
  uDemoCropAndScaleImages in 'Usando imagens, bitmaps e metarquivos\uDemoCropAndScaleImages.pas',
  uDemoRotateReflectSkew in 'Usando imagens, bitmaps e metarquivos\uDemoRotateReflectSkew.pas',
  uDemoInterpolationMode in 'Usando imagens, bitmaps e metarquivos\uDemoInterpolationMode.pas',
  uDemoThumbnails in 'Usando imagens, bitmaps e metarquivos\uDemoThumbnails.pas',
  uDemoCachedBitmap in 'Usando imagens, bitmaps e metarquivos\uDemoCachedBitmap.pas',
  uDemoAvoidAutomaticScaling in 'Usando imagens, bitmaps e metarquivos\uDemoAvoidAutomaticScaling.pas',
  uDemoReadWriteMetaData in 'Usando imagens, bitmaps e metarquivos\uDemoReadWriteMetaData.pas',
  uDemoListInstalledEncoders in 'Usando codificadores e decodificadores de imagens\uDemoListInstalledEncoders.pas',
  uDemoListInstalledDecoders in 'Usando codificadores e decodificadores de imagens\uDemoListInstalledDecoders.pas',
  uDemoGetEncoderClsid in 'Usando codificadores e decodificadores de imagens\uDemoGetEncoderClsid.pas',
  uDemoEncoderParameters in 'Usando codificadores e decodificadores de imagens\Parâmetros do codificador\uDemoEncoderParameters.pas',
  uDemoEncoderValue in 'Usando codificadores e decodificadores de imagens\Parâmetros do codificador\uDemoEncoderValue.pas',
  uDemoAllEncoderParameters in 'Usando codificadores e decodificadores de imagens\Parâmetros do codificador\uDemoAllEncoderParameters.pas',
  uDemoBmpToPng in 'Usando codificadores e decodificadores de imagens\uDemoBmpToPng.pas',
  uDemoJpegCompression in 'Usando codificadores e decodificadores de imagens\uDemoJpegCompression.pas',
  uDemoTransformJpeg in 'Usando codificadores e decodificadores de imagens\uDemoTransformJpeg.pas',
  uDemoCreateMultiFrame in 'Usando codificadores e decodificadores de imagens\uDemoCreateMultiFrame.pas',
  uDemoSemitransparentLines in 'Linhas e preenchimentos com mesclagem alfa\uDemoSemitransparentLines.pas',
  uDemoSemitransparentBrushes in 'Linhas e preenchimentos com mesclagem alfa\uDemoSemitransparentBrushes.pas',
  uDemoCompositingMode in 'Linhas e preenchimentos com mesclagem alfa\uDemoCompositingMode.pas',
  uDemoColorMatrixAlpha in 'Linhas e preenchimentos com mesclagem alfa\uDemoColorMatrixAlpha.pas',
  uDemoIndividualAlpha in 'Linhas e preenchimentos com mesclagem alfa\uDemoIndividualAlpha.pas',
  uDemoConstructingFonts in 'Usando texto e fontes\uDemoConstructingFonts.pas',
  uDemoDrawingText in 'Usando texto e fontes\uDemoDrawingText.pas',
  uDemoFormattingText in 'Usando texto e fontes\uDemoFormattingText.pas',
  uDemoInstalledFonts in 'Usando texto e fontes\uDemoInstalledFonts.pas',
  uDemoFontMetrics in 'Usando texto e fontes\uDemoFontMetrics.pas',
  uDemoAntialiasingText in 'Usando texto e fontes\uDemoAntialiasingText.pas',
  uDemoCardinalSplines in 'Construindo e desenhando curvas\uDemoCardinalSplines.pas',
  uDemoBezierSplines in 'Construindo e desenhando curvas\uDemoBezierSplines.pas',
  uDemoLinearGradient in 'Preenchendo formas com um pincel gradiente\uDemoLinearGradient.pas',
  uDemoPathGradient in 'Preenchendo formas com um pincel gradiente\uDemoPathGradient.pas',
  uDemoGradientGamma in 'Preenchendo formas com um pincel gradiente\uDemoGradientGamma.pas',
  uDemoCreateFigures in 'Construindo e desenhando caminhos\uDemoCreateFigures.pas',
  uDemoFillOpenFigures in 'Construindo e desenhando caminhos\uDemoFillOpenFigures.pas',
  uDemoGraphicsState in 'Usando contêineres gráficos\uDemoGraphicsState.pas',
  uDemoNestedContainers in 'Usando contêineres gráficos\uDemoNestedContainers.pas',
  uDemoWorldTransformations in 'Transformações\uDemoWorldTransformations.pas',
  uDemoTransformationOrder in 'Transformações\uDemoTransformationOrder.pas',
  uDemoHitTestRegion in 'Usando regiões\uDemoHitTestRegion.pas',
  uDemoClipRegion in 'Usando regiões\uDemoClipRegion.pas',
  uDemoColorMatrixTransform in 'Recolorir\uDemoColorMatrixTransform.pas',
  uDemoTranslatingColors in 'Recolorir\uDemoTranslatingColors.pas',
  uDemoScalingColors in 'Recolorir\uDemoScalingColors.pas',
  uDemoRotatingColors in 'Recolorir\uDemoRotatingColors.pas',
  uDemoShearingColors in 'Recolorir\uDemoShearingColors.pas',
  uDemoColorRemapTable in 'Recolorir\uDemoColorRemapTable.pas',
  uDemoPrintGdiPlusOutput in 'Impressão\uDemoPrintGdiPlusOutput.pas',
  uDemoAntialiasing in 'Melhorias\uDemoAntialiasing.pas',
  uDemoPixelFormatConversion in 'Melhorias\uDemoPixelFormatConversion.pas',
  uDemoHistogram in 'Melhorias\uDemoHistogram.pas',
  uDemo in 'uDemo.pas',
  uSourceCodeConverter in 'uSourceCodeConverter.pas',
  FMain in 'FMain.pas' {FormMain},
  Se7e.Drawing.Gdiplus.Colors in '..\..\src\Se7e.Drawing.Gdiplus.Colors.pas',
  Se7e.Drawing.Gdiplus.Graphics in '..\..\src\Se7e.Drawing.Gdiplus.Graphics.pas',
  Se7e.Drawing.Gdiplus in '..\..\src\Se7e.Drawing.Gdiplus.pas',
  Se7e.Drawing.Gdiplus.Types in '..\..\src\Se7e.Drawing.Gdiplus.Types.pas',
  Se7e.Drawing.Gdiplus.Utils in '..\..\src\Se7e.Drawing.Gdiplus.Utils.pas',
  Se7e.Drawing in '..\..\src\Se7e.Drawing.pas',
  Se7e.Drawing.Rectangle in '..\..\src\Se7e.Drawing.Rectangle.pas',
  Se7e.GdiPlusHelpers in '..\..\src\Se7e.GdiPlusHelpers.pas',
  Se7e.MathF in '..\..\src\Se7e.MathF.pas',
  Se7e.NonNullable in '..\..\src\Se7e.NonNullable.pas',
  Se7e.Nullable in '..\..\src\Se7e.Nullable.pas',
  Se7e.Numerics in '..\..\src\Se7e.Numerics.pas',
  Se7e.ReadOnly in '..\..\src\Se7e.ReadOnly.pas',
  Se7e.Span in '..\..\src\Se7e.Span.pas',
  Se7e.Windows.Win32.Graphics.Gdi in '..\..\src\Se7e.Windows.Win32.Graphics.Gdi.pas',
  Se7e.Windows.Win32.Graphics.GdiplusAPI in '..\..\src\Se7e.Windows.Win32.Graphics.GdiplusAPI.pas',
  Se7e.Windows.Win32.PInvokeCore in '..\..\src\Se7e.Windows.Win32.PInvokeCore.pas';

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
